#!/bin/bash
#
# Generate secret file .env for development.
# Idempotent: will not overwrite an existing .env unless --force is passed.
# Usage:
#   bash init_env.sh         # interactive
#   bash init_env.sh --force # overwrite existing .env
#   just init-env            # via Justfile

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STRIX_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$SCRIPT_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
    echo "[setup-env] .env already exists. Delete it first to regenerate."
    exit 0
fi

resolve_model() {
    local filename="$1"
    local results

    # Capture all matches; fail on zero or multiple
    mapfile -t results < <(find "$STRIX_DIR" -name "$filename" -type f 2>/dev/null)

    if [[ ${#results[@]} -eq 0 ]]; then
        echo "[setup-env] ERROR: '$filename' not found anywhere under $STRIX_DIR" >&2
        exit 1
    fi

    if [[ ${#results[@]} -gt 1 ]]; then
        echo "[setup-env] ERROR: Multiple '$filename' found - ambiguous:" >&2
        printf '  %s\n' "${results[@]}" >&2
        echo "  Remove duplicates or set paths manually in .env." >&2
        exit 1
    fi

    realpath "${results[0]}"
}

echo "Searching..."
TOKENIZER_PATH="$(resolve_model tokenizer.onnx)"
TRANSFORMER_PATH="$(resolve_model transformer.onnx)"

echo "Writing..."
cat > "$ENV_FILE" <<EOF
# Generated by init-env.sh - do not commit.

TOKENIZER_PATH=$TOKENIZER_PATH
TRANSFORMER_PATH=$TRANSFORMER_PATH
EOF

echo "Done! You should see an .env now."
