// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: strix.proto
// Protobuf C++ Version: 6.33.4

#ifndef strix_2eproto_2epb_2eh
#define strix_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_strix_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_strix_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_strix_2eproto;
}  // extern "C"
namespace proto {
enum CacheState : int;
extern const uint32_t CacheState_internal_data_[];
class CheckCacheRequest;
struct CheckCacheRequestDefaultTypeInternal;
extern CheckCacheRequestDefaultTypeInternal _CheckCacheRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CheckCacheRequest_class_data_;
class CheckCacheResponse;
struct CheckCacheResponseDefaultTypeInternal;
extern CheckCacheResponseDefaultTypeInternal _CheckCacheResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CheckCacheResponse_class_data_;
class SetCacheRequest;
struct SetCacheRequestDefaultTypeInternal;
extern SetCacheRequestDefaultTypeInternal _SetCacheRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SetCacheRequest_class_data_;
class SetCacheResponse;
struct SetCacheResponseDefaultTypeInternal;
extern SetCacheResponseDefaultTypeInternal _SetCacheResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull SetCacheResponse_class_data_;
}  // namespace proto
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::proto::CacheState_internal_data_>
    internal::EnumTraitsImpl::value<::proto::CacheState>;
}  // namespace protobuf
}  // namespace google

namespace proto {
enum CacheState : int {
  CACHE_STATE_UNSPECIFIED = 0,
  CACHE_STATE_HIT = 1,
  CACHE_STATE_MISS = 2,
  CACHE_STATE_PENDING = 3,
  CACHE_STATE_EXCEEDED = 4,
  CacheState_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CacheState_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CacheState_internal_data_[];
inline constexpr CacheState CacheState_MIN =
    static_cast<CacheState>(0);
inline constexpr CacheState CacheState_MAX =
    static_cast<CacheState>(4);
inline bool CacheState_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int CacheState_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CacheState_descriptor();
template <typename T>
const ::std::string& CacheState_Name(T value) {
  static_assert(::std::is_same<T, CacheState>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CacheState_Name().");
  return CacheState_Name(static_cast<CacheState>(value));
}
template <>
inline const ::std::string& CacheState_Name(CacheState value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CacheState_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool CacheState_Parse(
    ::absl::string_view name, CacheState* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CacheState>(CacheState_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class SetCacheResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.SetCacheResponse) */ {
 public:
  inline SetCacheResponse() : SetCacheResponse(nullptr) {}
  ~SetCacheResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SetCacheResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SetCacheResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetCacheResponse(::google::protobuf::internal::ConstantInitialized);

  inline SetCacheResponse(const SetCacheResponse& from) : SetCacheResponse(nullptr, from) {}
  inline SetCacheResponse(SetCacheResponse&& from) noexcept
      : SetCacheResponse(nullptr, ::std::move(from)) {}
  inline SetCacheResponse& operator=(const SetCacheResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetCacheResponse& operator=(SetCacheResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetCacheResponse& default_instance() {
    return *reinterpret_cast<const SetCacheResponse*>(
        &_SetCacheResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SetCacheResponse& a, SetCacheResponse& b) { a.Swap(&b); }
  inline void Swap(SetCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetCacheResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SetCacheResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetCacheResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetCacheResponse& from) { SetCacheResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SetCacheResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.SetCacheResponse"; }

  explicit SetCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SetCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetCacheResponse& from);
  SetCacheResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SetCacheResponse&& from) noexcept
      : SetCacheResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:proto.SetCacheResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SetCacheResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strix_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SetCacheResponse_class_data_;
// -------------------------------------------------------------------

class SetCacheRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.SetCacheRequest) */ {
 public:
  inline SetCacheRequest() : SetCacheRequest(nullptr) {}
  ~SetCacheRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SetCacheRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SetCacheRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SetCacheRequest(::google::protobuf::internal::ConstantInitialized);

  inline SetCacheRequest(const SetCacheRequest& from) : SetCacheRequest(nullptr, from) {}
  inline SetCacheRequest(SetCacheRequest&& from) noexcept
      : SetCacheRequest(nullptr, ::std::move(from)) {}
  inline SetCacheRequest& operator=(const SetCacheRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetCacheRequest& operator=(SetCacheRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetCacheRequest& default_instance() {
    return *reinterpret_cast<const SetCacheRequest*>(
        &_SetCacheRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SetCacheRequest& a, SetCacheRequest& b) { a.Swap(&b); }
  inline void Swap(SetCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetCacheRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SetCacheRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SetCacheRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SetCacheRequest& from) { SetCacheRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SetCacheRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.SetCacheRequest"; }

  explicit SetCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  SetCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetCacheRequest& from);
  SetCacheRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, SetCacheRequest&& from) noexcept
      : SetCacheRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUncachedPayloadFieldNumber = 2,
    kNodeIdFieldNumber = 1,
  };
  // bytes uncached_payload = 2;
  void clear_uncached_payload() ;
  const ::std::string& uncached_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_uncached_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_uncached_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_uncached_payload();
  void set_allocated_uncached_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_uncached_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_uncached_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_uncached_payload();

  public:
  // int32 node_id = 1;
  void clear_node_id() ;
  ::int32_t node_id() const;
  void set_node_id(::int32_t value);

  private:
  ::int32_t _internal_node_id() const;
  void _internal_set_node_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.SetCacheRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const SetCacheRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr uncached_payload_;
    ::int32_t node_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strix_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull SetCacheRequest_class_data_;
// -------------------------------------------------------------------

class CheckCacheResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CheckCacheResponse) */ {
 public:
  inline CheckCacheResponse() : CheckCacheResponse(nullptr) {}
  ~CheckCacheResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CheckCacheResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CheckCacheResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CheckCacheResponse(::google::protobuf::internal::ConstantInitialized);

  inline CheckCacheResponse(const CheckCacheResponse& from) : CheckCacheResponse(nullptr, from) {}
  inline CheckCacheResponse(CheckCacheResponse&& from) noexcept
      : CheckCacheResponse(nullptr, ::std::move(from)) {}
  inline CheckCacheResponse& operator=(const CheckCacheResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckCacheResponse& operator=(CheckCacheResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckCacheResponse& default_instance() {
    return *reinterpret_cast<const CheckCacheResponse*>(
        &_CheckCacheResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CheckCacheResponse& a, CheckCacheResponse& b) { a.Swap(&b); }
  inline void Swap(CheckCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckCacheResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckCacheResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CheckCacheResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CheckCacheResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CheckCacheResponse& from) { CheckCacheResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CheckCacheResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CheckCacheResponse"; }

  explicit CheckCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CheckCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CheckCacheResponse& from);
  CheckCacheResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CheckCacheResponse&& from) noexcept
      : CheckCacheResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCachedPayloadFieldNumber = 3,
    kCheckStateFieldNumber = 1,
    kNodeIdFieldNumber = 2,
  };
  // bytes cached_payload = 3;
  void clear_cached_payload() ;
  const ::std::string& cached_payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_cached_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_cached_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_cached_payload();
  void set_allocated_cached_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_cached_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_cached_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_cached_payload();

  public:
  // .proto.CacheState check_state = 1;
  void clear_check_state() ;
  ::proto::CacheState check_state() const;
  void set_check_state(::proto::CacheState value);

  private:
  ::proto::CacheState _internal_check_state() const;
  void _internal_set_check_state(::proto::CacheState value);

  public:
  // int32 node_id = 2;
  void clear_node_id() ;
  ::int32_t node_id() const;
  void set_node_id(::int32_t value);

  private:
  ::int32_t _internal_node_id() const;
  void _internal_set_node_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:proto.CheckCacheResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CheckCacheResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr cached_payload_;
    int check_state_;
    ::int32_t node_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strix_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CheckCacheResponse_class_data_;
// -------------------------------------------------------------------

class CheckCacheRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:proto.CheckCacheRequest) */ {
 public:
  inline CheckCacheRequest() : CheckCacheRequest(nullptr) {}
  ~CheckCacheRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CheckCacheRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CheckCacheRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CheckCacheRequest(::google::protobuf::internal::ConstantInitialized);

  inline CheckCacheRequest(const CheckCacheRequest& from) : CheckCacheRequest(nullptr, from) {}
  inline CheckCacheRequest(CheckCacheRequest&& from) noexcept
      : CheckCacheRequest(nullptr, ::std::move(from)) {}
  inline CheckCacheRequest& operator=(const CheckCacheRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline CheckCacheRequest& operator=(CheckCacheRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CheckCacheRequest& default_instance() {
    return *reinterpret_cast<const CheckCacheRequest*>(
        &_CheckCacheRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CheckCacheRequest& a, CheckCacheRequest& b) { a.Swap(&b); }
  inline void Swap(CheckCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CheckCacheRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CheckCacheRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CheckCacheRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CheckCacheRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CheckCacheRequest& from) { CheckCacheRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CheckCacheRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "proto.CheckCacheRequest"; }

  explicit CheckCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CheckCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CheckCacheRequest& from);
  CheckCacheRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CheckCacheRequest&& from) noexcept
      : CheckCacheRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPromptFieldNumber = 1,
  };
  // bytes prompt = 1;
  void clear_prompt() ;
  const ::std::string& prompt() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_prompt(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_prompt();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_prompt();
  void set_allocated_prompt(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_prompt() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_prompt(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_prompt();

  public:
  // @@protoc_insertion_point(class_scope:proto.CheckCacheRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CheckCacheRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr prompt_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_strix_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CheckCacheRequest_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CheckCacheRequest

// bytes prompt = 1;
inline void CheckCacheRequest::clear_prompt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prompt_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CheckCacheRequest::prompt() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CheckCacheRequest.prompt)
  return _internal_prompt();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CheckCacheRequest::set_prompt(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.prompt_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CheckCacheRequest.prompt)
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheRequest::mutable_prompt()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_prompt();
  // @@protoc_insertion_point(field_mutable:proto.CheckCacheRequest.prompt)
  return _s;
}
inline const ::std::string& CheckCacheRequest::_internal_prompt() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.prompt_.Get();
}
inline void CheckCacheRequest::_internal_set_prompt(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.prompt_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheRequest::_internal_mutable_prompt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.prompt_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CheckCacheRequest::release_prompt() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CheckCacheRequest.prompt)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.prompt_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.prompt_.Set("", GetArena());
  }
  return released;
}
inline void CheckCacheRequest::set_allocated_prompt(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.prompt_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.prompt_.IsDefault()) {
    _impl_.prompt_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CheckCacheRequest.prompt)
}

// -------------------------------------------------------------------

// CheckCacheResponse

// .proto.CacheState check_state = 1;
inline void CheckCacheResponse::clear_check_state() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.check_state_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::proto::CacheState CheckCacheResponse::check_state() const {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.check_state)
  return _internal_check_state();
}
inline void CheckCacheResponse::set_check_state(::proto::CacheState value) {
  _internal_set_check_state(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.check_state)
}
inline ::proto::CacheState CheckCacheResponse::_internal_check_state() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::proto::CacheState>(_impl_.check_state_);
}
inline void CheckCacheResponse::_internal_set_check_state(::proto::CacheState value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.check_state_ = value;
}

// int32 node_id = 2;
inline void CheckCacheResponse::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t CheckCacheResponse::node_id() const {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.node_id)
  return _internal_node_id();
}
inline void CheckCacheResponse::set_node_id(::int32_t value) {
  _internal_set_node_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.node_id)
}
inline ::int32_t CheckCacheResponse::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_;
}
inline void CheckCacheResponse::_internal_set_node_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = value;
}

// bytes cached_payload = 3;
inline void CheckCacheResponse::clear_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cached_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CheckCacheResponse::cached_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.CheckCacheResponse.cached_payload)
  return _internal_cached_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CheckCacheResponse::set_cached_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.cached_payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.CheckCacheResponse.cached_payload)
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheResponse::mutable_cached_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_cached_payload();
  // @@protoc_insertion_point(field_mutable:proto.CheckCacheResponse.cached_payload)
  return _s;
}
inline const ::std::string& CheckCacheResponse::_internal_cached_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cached_payload_.Get();
}
inline void CheckCacheResponse::_internal_set_cached_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cached_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CheckCacheResponse::_internal_mutable_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.cached_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CheckCacheResponse::release_cached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.CheckCacheResponse.cached_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.cached_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.cached_payload_.Set("", GetArena());
  }
  return released;
}
inline void CheckCacheResponse::set_allocated_cached_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.cached_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.cached_payload_.IsDefault()) {
    _impl_.cached_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.CheckCacheResponse.cached_payload)
}

// -------------------------------------------------------------------

// SetCacheRequest

// int32 node_id = 1;
inline void SetCacheRequest::clear_node_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t SetCacheRequest::node_id() const {
  // @@protoc_insertion_point(field_get:proto.SetCacheRequest.node_id)
  return _internal_node_id();
}
inline void SetCacheRequest::set_node_id(::int32_t value) {
  _internal_set_node_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:proto.SetCacheRequest.node_id)
}
inline ::int32_t SetCacheRequest::_internal_node_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.node_id_;
}
inline void SetCacheRequest::_internal_set_node_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.node_id_ = value;
}

// bytes uncached_payload = 2;
inline void SetCacheRequest::clear_uncached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uncached_payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& SetCacheRequest::uncached_payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:proto.SetCacheRequest.uncached_payload)
  return _internal_uncached_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void SetCacheRequest::set_uncached_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.uncached_payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:proto.SetCacheRequest.uncached_payload)
}
inline ::std::string* PROTOBUF_NONNULL SetCacheRequest::mutable_uncached_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_uncached_payload();
  // @@protoc_insertion_point(field_mutable:proto.SetCacheRequest.uncached_payload)
  return _s;
}
inline const ::std::string& SetCacheRequest::_internal_uncached_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.uncached_payload_.Get();
}
inline void SetCacheRequest::_internal_set_uncached_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.uncached_payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL SetCacheRequest::_internal_mutable_uncached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.uncached_payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE SetCacheRequest::release_uncached_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:proto.SetCacheRequest.uncached_payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.uncached_payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.uncached_payload_.Set("", GetArena());
  }
  return released;
}
inline void SetCacheRequest::set_allocated_uncached_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.uncached_payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.uncached_payload_.IsDefault()) {
    _impl_.uncached_payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.SetCacheRequest.uncached_payload)
}

// -------------------------------------------------------------------

// SetCacheResponse

// bool success = 1;
inline void SetCacheResponse::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool SetCacheResponse::success() const {
  // @@protoc_insertion_point(field_get:proto.SetCacheResponse.success)
  return _internal_success();
}
inline void SetCacheResponse::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:proto.SetCacheResponse.success)
}
inline bool SetCacheResponse::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void SetCacheResponse::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::proto::CacheState> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::proto::CacheState>() {
  return ::proto::CacheState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // strix_2eproto_2epb_2eh
