// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: strix.proto

#include "strix.pb.h"
#include "strix.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace proto {

static const char* CacheService_method_names[] = {
  "/proto.CacheService/CheckCache",
  "/proto.CacheService/SetCache",
};

std::unique_ptr< CacheService::Stub> CacheService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CacheService::Stub> stub(new CacheService::Stub(channel, options));
  return stub;
}

CacheService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckCache_(CacheService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetCache_(CacheService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CacheService::Stub::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::proto::CheckCacheResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckCache_, context, request, response);
}

void CacheService::Stub::async::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCache_, context, request, response, std::move(f));
}

void CacheService::Stub::async::CheckCache(::grpc::ClientContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckCache_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* CacheService::Stub::PrepareAsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::CheckCacheResponse, ::proto::CheckCacheRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckCache_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::CheckCacheResponse>* CacheService::Stub::AsyncCheckCacheRaw(::grpc::ClientContext* context, const ::proto::CheckCacheRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckCacheRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CacheService::Stub::SetCache(::grpc::ClientContext* context, const ::proto::SetCacheRequest& request, ::proto::SetCacheResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::SetCacheRequest, ::proto::SetCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetCache_, context, request, response);
}

void CacheService::Stub::async::SetCache(::grpc::ClientContext* context, const ::proto::SetCacheRequest* request, ::proto::SetCacheResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::SetCacheRequest, ::proto::SetCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetCache_, context, request, response, std::move(f));
}

void CacheService::Stub::async::SetCache(::grpc::ClientContext* context, const ::proto::SetCacheRequest* request, ::proto::SetCacheResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetCache_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::SetCacheResponse>* CacheService::Stub::PrepareAsyncSetCacheRaw(::grpc::ClientContext* context, const ::proto::SetCacheRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::SetCacheResponse, ::proto::SetCacheRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetCache_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::SetCacheResponse>* CacheService::Stub::AsyncSetCacheRaw(::grpc::ClientContext* context, const ::proto::SetCacheRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetCacheRaw(context, request, cq);
  result->StartCall();
  return result;
}

CacheService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::proto::CheckCacheRequest, ::proto::CheckCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::CheckCacheRequest* req,
             ::proto::CheckCacheResponse* resp) {
               return service->CheckCache(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CacheService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CacheService::Service, ::proto::SetCacheRequest, ::proto::SetCacheResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CacheService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::SetCacheRequest* req,
             ::proto::SetCacheResponse* resp) {
               return service->SetCache(ctx, req, resp);
             }, this)));
}

CacheService::Service::~Service() {
}

::grpc::Status CacheService::Service::CheckCache(::grpc::ServerContext* context, const ::proto::CheckCacheRequest* request, ::proto::CheckCacheResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CacheService::Service::SetCache(::grpc::ServerContext* context, const ::proto::SetCacheRequest* request, ::proto::SetCacheResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto
#include <grpcpp/ports_undef.inc>

