// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: strix.proto
// Protobuf C++ Version: 6.33.4

#include "strix.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace proto {

inline constexpr SetCacheResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        success_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SetCacheResponse::SetCacheResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SetCacheResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetCacheResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetCacheResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetCacheResponseDefaultTypeInternal() {}
  union {
    SetCacheResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetCacheResponseDefaultTypeInternal _SetCacheResponse_default_instance_;

inline constexpr SetCacheRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        uncached_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        node_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetCacheRequest::SetCacheRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(SetCacheRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetCacheRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetCacheRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetCacheRequestDefaultTypeInternal() {}
  union {
    SetCacheRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetCacheRequestDefaultTypeInternal _SetCacheRequest_default_instance_;

inline constexpr CheckCacheResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cached_payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        check_state_{static_cast< ::proto::CacheState >(0)},
        node_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CheckCacheResponse::CheckCacheResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CheckCacheResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CheckCacheResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckCacheResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckCacheResponseDefaultTypeInternal() {}
  union {
    CheckCacheResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckCacheResponseDefaultTypeInternal _CheckCacheResponse_default_instance_;

inline constexpr CheckCacheRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        prompt_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR CheckCacheRequest::CheckCacheRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CheckCacheRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CheckCacheRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckCacheRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckCacheRequestDefaultTypeInternal() {}
  union {
    CheckCacheRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckCacheRequestDefaultTypeInternal _CheckCacheRequest_default_instance_;
}  // namespace proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_strix_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_strix_2eproto = nullptr;
const ::uint32_t
    TableStruct_strix_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheRequest, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheRequest, _impl_.prompt_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheResponse, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheResponse, _impl_.check_state_),
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheResponse, _impl_.node_id_),
        PROTOBUF_FIELD_OFFSET(::proto::CheckCacheResponse, _impl_.cached_payload_),
        1,
        2,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SetCacheRequest, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SetCacheRequest, _impl_.node_id_),
        PROTOBUF_FIELD_OFFSET(::proto::SetCacheRequest, _impl_.uncached_payload_),
        1,
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::proto::SetCacheResponse, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::proto::SetCacheResponse, _impl_.success_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::proto::CheckCacheRequest)},
        {5, sizeof(::proto::CheckCacheResponse)},
        {14, sizeof(::proto::SetCacheRequest)},
        {21, sizeof(::proto::SetCacheResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::proto::_CheckCacheRequest_default_instance_._instance,
    &::proto::_CheckCacheResponse_default_instance_._instance,
    &::proto::_SetCacheRequest_default_instance_._instance,
    &::proto::_SetCacheResponse_default_instance_._instance,
};
const char descriptor_table_protodef_strix_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013strix.proto\022\005proto\"#\n\021CheckCacheReques"
    "t\022\016\n\006prompt\030\001 \001(\014\"e\n\022CheckCacheResponse\022"
    "&\n\013check_state\030\001 \001(\0162\021.proto.CacheState\022"
    "\017\n\007node_id\030\002 \001(\005\022\026\n\016cached_payload\030\003 \001(\014"
    "\"<\n\017SetCacheRequest\022\017\n\007node_id\030\001 \001(\005\022\030\n\020"
    "uncached_payload\030\002 \001(\014\"#\n\020SetCacheRespon"
    "se\022\017\n\007success\030\001 \001(\010*\207\001\n\nCacheState\022\033\n\027CA"
    "CHE_STATE_UNSPECIFIED\020\000\022\023\n\017CACHE_STATE_H"
    "IT\020\001\022\024\n\020CACHE_STATE_MISS\020\002\022\027\n\023CACHE_STAT"
    "E_PENDING\020\003\022\030\n\024CACHE_STATE_EXCEEDED\020\0042\216\001"
    "\n\014CacheService\022A\n\nCheckCache\022\030.proto.Che"
    "ckCacheRequest\032\031.proto.CheckCacheRespons"
    "e\022;\n\010SetCache\022\026.proto.SetCacheRequest\032\027."
    "proto.SetCacheResponseB\022Z\020strix/gateway/"
    "pbb\006proto3"
};
static ::absl::once_flag descriptor_table_strix_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_strix_2eproto = {
    false,
    false,
    570,
    descriptor_table_protodef_strix_2eproto,
    "strix.proto",
    &descriptor_table_strix_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_strix_2eproto::offsets,
    file_level_enum_descriptors_strix_2eproto,
    file_level_service_descriptors_strix_2eproto,
};
namespace proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CacheState_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_strix_2eproto);
  return file_level_enum_descriptors_strix_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CacheState_internal_data_[] = {
    327680u, 0u, };
// ===================================================================

class CheckCacheRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CheckCacheRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CheckCacheRequest, _impl_._has_bits_);
};

CheckCacheRequest::CheckCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckCacheRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.CheckCacheRequest)
}
PROTOBUF_NDEBUG_INLINE CheckCacheRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::CheckCacheRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        prompt_(arena, from.prompt_) {}

CheckCacheRequest::CheckCacheRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CheckCacheRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckCacheRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CheckCacheRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:proto.CheckCacheRequest)
}
PROTOBUF_NDEBUG_INLINE CheckCacheRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        prompt_(arena) {}

inline void CheckCacheRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CheckCacheRequest::~CheckCacheRequest() {
  // @@protoc_insertion_point(destructor:proto.CheckCacheRequest)
  SharedDtor(*this);
}
inline void CheckCacheRequest::SharedDtor(MessageLite& self) {
  CheckCacheRequest& this_ = static_cast<CheckCacheRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.prompt_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CheckCacheRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CheckCacheRequest(arena);
}
constexpr auto CheckCacheRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CheckCacheRequest),
                                            alignof(CheckCacheRequest));
}
constexpr auto CheckCacheRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CheckCacheRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CheckCacheRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CheckCacheRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CheckCacheRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CheckCacheRequest>(), &CheckCacheRequest::ByteSizeLong,
              &CheckCacheRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CheckCacheRequest, _impl_._cached_size_),
          false,
      },
      &CheckCacheRequest::kDescriptorMethods,
      &descriptor_table_strix_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CheckCacheRequest_class_data_ =
        CheckCacheRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CheckCacheRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CheckCacheRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CheckCacheRequest_class_data_.tc_table);
  return CheckCacheRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
CheckCacheRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CheckCacheRequest, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CheckCacheRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::CheckCacheRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes prompt = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CheckCacheRequest, _impl_.prompt_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes prompt = 1;
    {PROTOBUF_FIELD_OFFSET(CheckCacheRequest, _impl_.prompt_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CheckCacheRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.CheckCacheRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.prompt_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CheckCacheRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CheckCacheRequest& this_ = static_cast<const CheckCacheRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CheckCacheRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CheckCacheRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.CheckCacheRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bytes prompt = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_prompt().empty()) {
      const ::std::string& _s = this_._internal_prompt();
      target = stream->WriteBytesMaybeAliased(1, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.CheckCacheRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CheckCacheRequest::ByteSizeLong(const MessageLite& base) {
  const CheckCacheRequest& this_ = static_cast<const CheckCacheRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CheckCacheRequest::ByteSizeLong() const {
  const CheckCacheRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.CheckCacheRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bytes prompt = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_prompt().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_prompt());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CheckCacheRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CheckCacheRequest*>(&to_msg);
  auto& from = static_cast<const CheckCacheRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.CheckCacheRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!from._internal_prompt().empty()) {
      _this->_internal_set_prompt(from._internal_prompt());
    } else {
      if (_this->_impl_.prompt_.IsDefault()) {
        _this->_internal_set_prompt("");
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CheckCacheRequest::CopyFrom(const CheckCacheRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.CheckCacheRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CheckCacheRequest::InternalSwap(CheckCacheRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.prompt_, &other->_impl_.prompt_, arena);
}

::google::protobuf::Metadata CheckCacheRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CheckCacheResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CheckCacheResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_._has_bits_);
};

CheckCacheResponse::CheckCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckCacheResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.CheckCacheResponse)
}
PROTOBUF_NDEBUG_INLINE CheckCacheResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::CheckCacheResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        cached_payload_(arena, from.cached_payload_) {}

CheckCacheResponse::CheckCacheResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CheckCacheResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckCacheResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CheckCacheResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, check_state_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, check_state_),
           offsetof(Impl_, node_id_) -
               offsetof(Impl_, check_state_) +
               sizeof(Impl_::node_id_));

  // @@protoc_insertion_point(copy_constructor:proto.CheckCacheResponse)
}
PROTOBUF_NDEBUG_INLINE CheckCacheResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        cached_payload_(arena) {}

inline void CheckCacheResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, check_state_),
           0,
           offsetof(Impl_, node_id_) -
               offsetof(Impl_, check_state_) +
               sizeof(Impl_::node_id_));
}
CheckCacheResponse::~CheckCacheResponse() {
  // @@protoc_insertion_point(destructor:proto.CheckCacheResponse)
  SharedDtor(*this);
}
inline void CheckCacheResponse::SharedDtor(MessageLite& self) {
  CheckCacheResponse& this_ = static_cast<CheckCacheResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.cached_payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CheckCacheResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CheckCacheResponse(arena);
}
constexpr auto CheckCacheResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CheckCacheResponse),
                                            alignof(CheckCacheResponse));
}
constexpr auto CheckCacheResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CheckCacheResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CheckCacheResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CheckCacheResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CheckCacheResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CheckCacheResponse>(), &CheckCacheResponse::ByteSizeLong,
              &CheckCacheResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_._cached_size_),
          false,
      },
      &CheckCacheResponse::kDescriptorMethods,
      &descriptor_table_strix_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CheckCacheResponse_class_data_ =
        CheckCacheResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CheckCacheResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CheckCacheResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CheckCacheResponse_class_data_.tc_table);
  return CheckCacheResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2>
CheckCacheResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CheckCacheResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::CheckCacheResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .proto.CacheState check_state = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CheckCacheResponse, _impl_.check_state_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.check_state_)}},
    // int32 node_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CheckCacheResponse, _impl_.node_id_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.node_id_)}},
    // bytes cached_payload = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.cached_payload_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .proto.CacheState check_state = 1;
    {PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.check_state_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // int32 node_id = 2;
    {PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.node_id_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes cached_payload = 3;
    {PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.cached_payload_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CheckCacheResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.CheckCacheResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.cached_payload_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000006U)) {
    ::memset(&_impl_.check_state_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.node_id_) -
        reinterpret_cast<char*>(&_impl_.check_state_)) + sizeof(_impl_.node_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CheckCacheResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CheckCacheResponse& this_ = static_cast<const CheckCacheResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CheckCacheResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CheckCacheResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.CheckCacheResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .proto.CacheState check_state = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_check_state() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_check_state(), target);
    }
  }

  // int32 node_id = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_node_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
              stream, this_._internal_node_id(), target);
    }
  }

  // bytes cached_payload = 3;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_cached_payload().empty()) {
      const ::std::string& _s = this_._internal_cached_payload();
      target = stream->WriteBytesMaybeAliased(3, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.CheckCacheResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CheckCacheResponse::ByteSizeLong(const MessageLite& base) {
  const CheckCacheResponse& this_ = static_cast<const CheckCacheResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CheckCacheResponse::ByteSizeLong() const {
  const CheckCacheResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.CheckCacheResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // bytes cached_payload = 3;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_cached_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_cached_payload());
      }
    }
    // .proto.CacheState check_state = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_check_state() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_check_state());
      }
    }
    // int32 node_id = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_node_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_node_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CheckCacheResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CheckCacheResponse*>(&to_msg);
  auto& from = static_cast<const CheckCacheResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.CheckCacheResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_cached_payload().empty()) {
        _this->_internal_set_cached_payload(from._internal_cached_payload());
      } else {
        if (_this->_impl_.cached_payload_.IsDefault()) {
          _this->_internal_set_cached_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_check_state() != 0) {
        _this->_impl_.check_state_ = from._impl_.check_state_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_node_id() != 0) {
        _this->_impl_.node_id_ = from._impl_.node_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CheckCacheResponse::CopyFrom(const CheckCacheResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.CheckCacheResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CheckCacheResponse::InternalSwap(CheckCacheResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.cached_payload_, &other->_impl_.cached_payload_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.node_id_)
      + sizeof(CheckCacheResponse::_impl_.node_id_)
      - PROTOBUF_FIELD_OFFSET(CheckCacheResponse, _impl_.check_state_)>(
          reinterpret_cast<char*>(&_impl_.check_state_),
          reinterpret_cast<char*>(&other->_impl_.check_state_));
}

::google::protobuf::Metadata CheckCacheResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetCacheRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SetCacheRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_._has_bits_);
};

SetCacheRequest::SetCacheRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetCacheRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SetCacheRequest)
}
PROTOBUF_NDEBUG_INLINE SetCacheRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::proto::SetCacheRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        uncached_payload_(arena, from.uncached_payload_) {}

SetCacheRequest::SetCacheRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const SetCacheRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetCacheRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SetCacheRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.node_id_ = from._impl_.node_id_;

  // @@protoc_insertion_point(copy_constructor:proto.SetCacheRequest)
}
PROTOBUF_NDEBUG_INLINE SetCacheRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        uncached_payload_(arena) {}

inline void SetCacheRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.node_id_ = {};
}
SetCacheRequest::~SetCacheRequest() {
  // @@protoc_insertion_point(destructor:proto.SetCacheRequest)
  SharedDtor(*this);
}
inline void SetCacheRequest::SharedDtor(MessageLite& self) {
  SetCacheRequest& this_ = static_cast<SetCacheRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.uncached_payload_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SetCacheRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SetCacheRequest(arena);
}
constexpr auto SetCacheRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SetCacheRequest),
                                            alignof(SetCacheRequest));
}
constexpr auto SetCacheRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SetCacheRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SetCacheRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SetCacheRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SetCacheRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SetCacheRequest>(), &SetCacheRequest::ByteSizeLong,
              &SetCacheRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_._cached_size_),
          false,
      },
      &SetCacheRequest::kDescriptorMethods,
      &descriptor_table_strix_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SetCacheRequest_class_data_ =
        SetCacheRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SetCacheRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SetCacheRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SetCacheRequest_class_data_.tc_table);
  return SetCacheRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
SetCacheRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SetCacheRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SetCacheRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bytes uncached_payload = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_.uncached_payload_)}},
    // int32 node_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SetCacheRequest, _impl_.node_id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_.node_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 node_id = 1;
    {PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_.node_id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // bytes uncached_payload = 2;
    {PROTOBUF_FIELD_OFFSET(SetCacheRequest, _impl_.uncached_payload_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SetCacheRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SetCacheRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.uncached_payload_.ClearNonDefaultToEmpty();
  }
  _impl_.node_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SetCacheRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SetCacheRequest& this_ = static_cast<const SetCacheRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SetCacheRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SetCacheRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SetCacheRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // int32 node_id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (this_._internal_node_id() != 0) {
      target =
          ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
              stream, this_._internal_node_id(), target);
    }
  }

  // bytes uncached_payload = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_uncached_payload().empty()) {
      const ::std::string& _s = this_._internal_uncached_payload();
      target = stream->WriteBytesMaybeAliased(2, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SetCacheRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SetCacheRequest::ByteSizeLong(const MessageLite& base) {
  const SetCacheRequest& this_ = static_cast<const SetCacheRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SetCacheRequest::ByteSizeLong() const {
  const SetCacheRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SetCacheRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // bytes uncached_payload = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_uncached_payload().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_uncached_payload());
      }
    }
    // int32 node_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (this_._internal_node_id() != 0) {
        total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
            this_._internal_node_id());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SetCacheRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SetCacheRequest*>(&to_msg);
  auto& from = static_cast<const SetCacheRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SetCacheRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_uncached_payload().empty()) {
        _this->_internal_set_uncached_payload(from._internal_uncached_payload());
      } else {
        if (_this->_impl_.uncached_payload_.IsDefault()) {
          _this->_internal_set_uncached_payload("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (from._internal_node_id() != 0) {
        _this->_impl_.node_id_ = from._impl_.node_id_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SetCacheRequest::CopyFrom(const SetCacheRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SetCacheRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetCacheRequest::InternalSwap(SetCacheRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uncached_payload_, &other->_impl_.uncached_payload_, arena);
  swap(_impl_.node_id_, other->_impl_.node_id_);
}

::google::protobuf::Metadata SetCacheRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetCacheResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<SetCacheResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SetCacheResponse, _impl_._has_bits_);
};

SetCacheResponse::SetCacheResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetCacheResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:proto.SetCacheResponse)
}
SetCacheResponse::SetCacheResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const SetCacheResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, SetCacheResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE SetCacheResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void SetCacheResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
SetCacheResponse::~SetCacheResponse() {
  // @@protoc_insertion_point(destructor:proto.SetCacheResponse)
  SharedDtor(*this);
}
inline void SetCacheResponse::SharedDtor(MessageLite& self) {
  SetCacheResponse& this_ = static_cast<SetCacheResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL SetCacheResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) SetCacheResponse(arena);
}
constexpr auto SetCacheResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SetCacheResponse),
                                            alignof(SetCacheResponse));
}
constexpr auto SetCacheResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_SetCacheResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &SetCacheResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<SetCacheResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &SetCacheResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<SetCacheResponse>(), &SetCacheResponse::ByteSizeLong,
              &SetCacheResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(SetCacheResponse, _impl_._cached_size_),
          false,
      },
      &SetCacheResponse::kDescriptorMethods,
      &descriptor_table_strix_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull SetCacheResponse_class_data_ =
        SetCacheResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
SetCacheResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&SetCacheResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(SetCacheResponse_class_data_.tc_table);
  return SetCacheResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
SetCacheResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SetCacheResponse, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    SetCacheResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::proto::SetCacheResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SetCacheResponse, _impl_.success_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(SetCacheResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(SetCacheResponse, _impl_.success_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void SetCacheResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.SetCacheResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL SetCacheResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const SetCacheResponse& this_ = static_cast<const SetCacheResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL SetCacheResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const SetCacheResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:proto.SetCacheResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool success = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_success() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_success(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.SetCacheResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t SetCacheResponse::ByteSizeLong(const MessageLite& base) {
  const SetCacheResponse& this_ = static_cast<const SetCacheResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t SetCacheResponse::ByteSizeLong() const {
  const SetCacheResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:proto.SetCacheResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // bool success = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (this_._internal_success() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void SetCacheResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<SetCacheResponse*>(&to_msg);
  auto& from = static_cast<const SetCacheResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:proto.SetCacheResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (from._internal_success() != 0) {
      _this->_impl_.success_ = from._impl_.success_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void SetCacheResponse::CopyFrom(const SetCacheResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:proto.SetCacheResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetCacheResponse::InternalSwap(SetCacheResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata SetCacheResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_strix_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
